### ISSUE TITLE
Apps VPN selection UI is not shown

### ISSUE THREAD

**Issue by A-Shahbazi** [guardianproject/orbot#167]
The dialog which should be shown to choose apps is not shown in my device with kitkat rom.
It asks for permission to initiate the vpn but after that nothing happens and apps can't use internet.
I used Orbot 16.0.2 from fdroid.
Here's relevant part of `adb logcat`:
```
I/Timeline( 2760): Timeline: Activity_launch_request id:org.torproject.android time:1442290
I/ActivityManager(  605): START u0 {cmp=org.torproject.android/.vpn.VPNEnableActivity} from pid 2760
D/VPNEnableActivity( 2760): prompting user to start Orbot VPN
D/VPNEnableActivity( 2760): VPN enabled, starting Tor...
I/ActivityManager(  605): Displayed org.torproject.android/.vpn.VPNEnableActivity: +238ms
D/OrbotVpnService( 2760): starting OrbotVPNService service!
W/System.err( 2760): java.net.SocketException: Socket closed
W/System.err( 2760): 	at libcore.io.Posix.accept(Native Method)
W/System.err( 2760): 	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55)
W/System.err( 2760): 	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98)
W/System.err( 2760): 	at java.net.ServerSocket.implAccept(ServerSocket.java:203)
W/System.err( 2760): 	at java.net.ServerSocket.accept(ServerSocket.java:128)
W/System.err( 2760): 	at com.runjva.sourceforge.jsocks.protocol.ProxyServer.start(ProxyServer.java:186)
W/System.err( 2760): 	at org.torproject.android.service.vpn.OrbotVpnManager$1.run(OrbotVpnManager.java:182)
I/OrbotVpnService( 2760): PDNSD: 0
D/Vpn     (  605): setting state=CONNECTING, reason=establish
D/VpnJni  (  605): Address added on tun0: 192.168.200.1/32
W/InputMethodManagerService(  605): Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41f2cce8 (uid=10094 pid=2760)
I/Vpn     (  605): Established by org.torproject.android on tun0
D/Vpn     (  605): setting state=AUTHENTICATING, reason=establish
D/Tun2Socks( 2760): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.129
D/Tun2Socks( 2760): NOTICE(tun2socks): entering event loop
I/Timeline(  605): Timeline: Activity_windows_visible id: ActivityRecord{424a9f88 u0 org.torproject.android/.vpn.VPNEnableActivity t9 f} time:1443373
I/Timeline(  605): Timeline: Activity_windows_visible id: ActivityRecord{42389510 u0 org.torproject.android/.OrbotMainActivity t9} time:1443393
I/Timeline( 2760): Timeline: Activity_idle id: android.os.BinderProxy@41edbf60 time:1443806
D/Tun2Socks( 2760): INFO(tun2socks): UDP: from device 52 bytes
D/Orbot   ( 2760): orConnStatus (kramse3): CLOSED
D/Tun2Socks( 2760): INFO(tun2socks): UDP: from device 60 bytes
D/Tun2Socks( 2760): INFO(tun2socks): UDP: from device 40 bytes
D/Tun2Socks( 2760): INFO(tun2socks): UDP: from device 227 bytes
D/Orbot   ( 2760): Circuit (21) LAUNCHED: 
D/Orbot   ( 2760): orConnStatus (kramse3): LAUNCHED
D/Orbot   ( 2760): Circuit (6) CLOSED: kramse3
D/Orbot   ( 2760): Circuit (12) CLOSED: kramse3 > idideditheconfig > Unnamed
D/Orbot   ( 2760): Circuit (8) CLOSED: kramse3 > ididedittheconfig > modio1
D/Orbot   ( 2760): Circuit (17) CLOSED: kramse3 > xmmswap > dpjp06TorExit
D/Orbot   ( 2760): Circuit (9) CLOSED: kramse3 > DETor02 > BrassHornExit02
D/Orbot   ( 2760): Circuit (13) CLOSED: kramse3 > drazisil > doof
D/Orbot   ( 2760): Circuit (10) CLOSED: kramse3 > h0mer > freki
D/Orbot   ( 2760): Circuit (16) CLOSED: kramse3 > dc6jgk7b > niftyrat
D/Orbot   ( 2760): Circuit (19) CLOSED: kramse3 > KagamineLenAiKotoba > marylou2
D/Orbot   ( 2760): Circuit (15) CLOSED: kramse3 > isthistherealworld > sofia
D/Orbot   ( 2760): Circuit (14) CLOSED: kramse3 > BostonSneakernet > kbtr6lv
D/Orbot   ( 2760): Circuit (20) CLOSED: kramse3 > gyuhgyug > RSFPressFreedom
D/Orbot   ( 2760): Circuit (18) CLOSED: kramse3 > KAMIKAZE > argenla
D/Orbot   ( 2760): Circuit (22) LAUNCHED: 
D/Orbot   ( 2760): Circuit (23) LAUNCHED: 
D/Orbot   ( 2760): Circuit (24) LAUNCHED: 
D/Orbot   ( 2760): Circuit (25) LAUNCHED: 
```

**Comment by bitmold** [comment]
This isn't a bug, you can only choose apps on Lollipop (API 21) and up. With KitKat, you can still enable VPN mode but it's for the entire system.
