### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getCanonicalPath()

### ISSUE THREAD

**Issue by pgerber** [guardianproject/orbot#201]
I tried the armeabi-v7a build and the universal build of 16.0.6-BETA-1-tor-0.3.5.8. Both fail with this error:

```
checking binary version: 0.3.4.9-openssl1.0.2p
upgrading binaries to latest version: 0.3.5.8-rc-openssl1.0.2p
updating settings in Tor service
updating torrc custom configuration...
success.
Waiting for control port...
checking binary version: 0.3.4.9-openssl1.0.2p
Orbot is starting…
Orbot is starting…
updating settings in Tor service
updating torrc custom configuration...
success.
Orbot is starting…
Unable to start Tor: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getCanonicalPath()' on a null object reference
```

**Comment by n8fr8** [comment]
can you try a clean install to see if any better?

**Comment by n8fr8** [comment]
the " 0.3.4.9-openssl1.0.2p" seems like you upgraded from the last build, and then there was some confusion somewhere...

Also what device / OS? Thanks!

**Comment by pgerber** [comment]
Clean install doesn't make a difference, unfortunately.

Device info:
* Model: Motorola One
* Android version: 9

I also grabbed the logcat output covering the installation and first start: [logcat.txt](https://github.com/n8fr8/orbot/files/2998418/logcat.txt)

**Comment by n8fr8** [comment]
Thanks so much!

**Comment by n8fr8** [comment]
What is strange is that my primary test device is a Nokia 6.1 Android One phone, very similar to the Motorola One, and it works fine. I wonder what the difference might be....

Are you installing the Orbot in the default, internal space, or somehow running it off of SD / External Storage?

**Comment by yilmzfurkan** [comment]
@n8fr8 I have the same problem, first installed over the old installation didn't worked uninstalled and clean installed same error. My device is Samsung Galaxy S8+ (Android 9.0)

**Comment by pgerber** [comment]
> Are you installing the Orbot in the default, internal space, or somehow running it off of SD / External Storage?

Turns out Orbot was indeed installed on the external storage. I uninstalled it , ejected to storage and then reinstalled it. Still same issue.

**Comment by pgerber** [comment]
Tested it on a second device, a Samsung Galaxy 6, running Lineage OS 16.0 (Android 9). Same issue there.

I think this the interesting part:

```
03-23 23:35:46.753  4386  4972 E TorNativeLoader: /data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/lib/armeabi/tor.so (No such file or directory)
```

I checked the filesystem (`find / -name tor.so`) and there is no `tor.so` to be found. However, it appears to be in `/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/base.apk`.


Full logcat:

```
03-23 23:35:46.359  4386  4386 I TorService: onCreate end
03-23 23:35:46.366  4386  4972 D Orbot   : checking binary version: null
03-23 23:35:46.366  4386  4972 D Orbot   : upgrading binaries to latest version: 0.3.5.8-rc-openssl1.0.2p
03-23 23:35:46.751  4386  4972 D TorBinary: listing native files
03-23 23:35:46.751  4386  4972 D TorBinary: /data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/lib/arm/libtun2socks.so
03-23 23:35:46.753  4386  4972 E TorNativeLoader: /data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/lib/armeabi/tor.so (No such file or directory)
03-23 23:35:47.048  4386  4972 D Orbot   : updating settings in Tor service
03-23 23:35:47.053  4386  4972 D Orbot   : updating torrc custom configuration...
03-23 23:35:47.053  4386  4972 D Orbot   : torrc.custom=ControlPortWriteToFile /data/data/org.torproject.android/app_bin/control.txt
03-23 23:35:47.053  4386  4972 D Orbot   : SOCKSPort 9050  IPv6Traffic PreferIPv6 
03-23 23:35:47.053  4386  4972 D Orbot   : SafeSocks 0
03-23 23:35:47.053  4386  4972 D Orbot   : TestSocks 0
03-23 23:35:47.053  4386  4972 D Orbot   : HTTPTunnelPort 8118  IPv6Traffic PreferIPv6 
03-23 23:35:47.053  4386  4972 D Orbot   : ReducedConnectionPadding 1
03-23 23:35:47.053  4386  4972 D Orbot   : TransPort 9040
03-23 23:35:47.053  4386  4972 D Orbot   : DNSPort 5400
03-23 23:35:47.053  4386  4972 D Orbot   : VirtualAddrNetwork 10.192.0.0/10
03-23 23:35:47.053  4386  4972 D Orbot   : AutomapHostsOnResolve 1
03-23 23:35:47.053  4386  4972 D Orbot   : DisableNetwork 0
03-23 23:35:47.053  4386  4972 D Orbot   : Log debug syslog
03-23 23:35:47.053  4386  4972 D Orbot   : Log info syslog
03-23 23:35:47.053  4386  4972 D Orbot   : SafeLogging 0
03-23 23:35:47.053  4386  4972 D Orbot   : UseBridges 0
03-23 23:35:47.053  4386  4972 D Orbot   : GeoIPFile /data/data/org.torproject.android/app_bin/geoip
03-23 23:35:47.053  4386  4972 D Orbot   : GeoIPv6File /data/data/org.torproject.android/app_bin/geoip6
03-23 23:35:47.053  4386  4972 D Orbot   : StrictNodes 0
03-23 23:35:47.053  4386  4972 D Orbot   : Sandbox 1
03-23 23:35:47.055  4386  4972 D Orbot   : success.
03-23 23:35:47.055  4386  4972 D Orbot   : Waiting for control port...
03-23 23:35:47.055  4386  4972 D Orbot   : Control Port config file does not yet exist (waiting for tor): /data/data/org.torproject.android/app_bin/control.txt
03-23 23:35:47.192   384   384 E WifiHAL : wifi_get_link_stats: requestResponse Error:-3
03-23 23:35:47.194  1684  1798 E WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_SUPPORTED, .description = }
03-23 23:35:47.377  4386  4973 D Orbot   : checking binary version: null
03-23 23:35:47.383  4386  4973 D Orbot   : Orbot is starting…
03-23 23:35:47.387  4386  4973 D Orbot   : updating settings in Tor service
03-23 23:35:47.389  4386  4973 D Orbot   : updating torrc custom configuration...
03-23 23:35:47.389  4386  4973 D Orbot   : torrc.custom=ControlPortWriteToFile /data/data/org.torproject.android/app_bin/control.txt
03-23 23:35:47.389  4386  4973 D Orbot   : SOCKSPort 9050  IPv6Traffic PreferIPv6 
03-23 23:35:47.389  4386  4973 D Orbot   : SafeSocks 0
03-23 23:35:47.389  4386  4973 D Orbot   : TestSocks 0
03-23 23:35:47.389  4386  4973 D Orbot   : HTTPTunnelPort 8118  IPv6Traffic PreferIPv6 
03-23 23:35:47.389  4386  4973 D Orbot   : ReducedConnectionPadding 1
03-23 23:35:47.389  4386  4973 D Orbot   : TransPort 9040
03-23 23:35:47.389  4386  4973 D Orbot   : DNSPort 5400
03-23 23:35:47.389  4386  4973 D Orbot   : VirtualAddrNetwork 10.192.0.0/10
03-23 23:35:47.389  4386  4973 D Orbot   : AutomapHostsOnResolve 1
03-23 23:35:47.389  4386  4973 D Orbot   : DisableNetwork 0
03-23 23:35:47.389  4386  4973 D Orbot   : Log debug syslog
03-23 23:35:47.389  4386  4973 D Orbot   : Log info syslog
03-23 23:35:47.389  4386  4973 D Orbot   : SafeLogging 0
03-23 23:35:47.389  4386  4973 D Orbot   : UseBridges 0
03-23 23:35:47.389  4386  4973 D Orbot   : GeoIPFile /data/data/org.torproject.android/app_bin/geoip
03-23 23:35:47.389  4386  4973 D Orbot   : GeoIPv6File /data/data/org.torproject.android/app_bin/geoip6
03-23 23:35:47.389  4386  4973 D Orbot   : StrictNodes 0
03-23 23:35:47.389  4386  4973 D Orbot   : Sandbox 1
03-23 23:35:47.390  4386  4973 D torResources: deleting existing torrc.custom
03-23 23:35:47.390  4386  4973 D Orbot   : success.
03-23 23:35:47.391  4386  4973 E Orbot   : Unable to start Tor: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getCanonicalPath()' on a null object reference
03-23 23:35:47.391  4386  4973 E Orbot   : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getCanonicalPath()' on a null object reference
03-23 23:35:47.391  4386  4973 E Orbot   : 	at org.torproject.android.service.TorService.runTorShellCmd(TorService.java:864)
03-23 23:35:47.391  4386  4973 E Orbot   : 	at org.torproject.android.service.TorService.startTor(TorService.java:787)
03-23 23:35:47.391  4386  4973 E Orbot   : 	at org.torproject.android.service.TorService.access$200(TorService.java:81)
03-23 23:35:47.391  4386  4973 E Orbot   : 	at org.torproject.android.service.TorService$IncomingIntentRouter.run(TorService.java:375)
03-23 23:35:47.391  4386  4973 E Orbot   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-23 23:35:47.391  4386  4973 E Orbot   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-23 23:35:47.391  4386  4973 E Orbot   : 	at java.lang.Thread.run(Thread.java:764)
03-23 23:35:48.056  4386  4972 D Orbot   : Control Port config file does not yet exist (waiting for tor): /data/data/org.torproject.android/app_bin/control.txt
03-23 23:35:49.057  4386  4972 D Orbot   : Control Port config file does not yet exist (waiting for tor): /data/data/org.torproject.android/app_bin/control.txt
```

Content of `/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==`: 

```
# find /data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw\=\=/                                                                                                                 
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/lib
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/lib/arm
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/lib/arm/libtun2socks.so
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/oat
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/oat/arm
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/oat/arm/base.odex
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/oat/arm/base.vdex
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/oat/arm/base.art
/data/app/org.torproject.android-6iO22l4k3C9CPdAeO2ttdw==/base.apk
```

**Comment by n8fr8** [comment]
Actually just found one NPE on Galaxy S6 running default Android 7.x OS...

**Comment by n8fr8** [comment]
Alright I think figured it out... 14 hours later!

Please try this build, either the Universal, or the arm64-v8a I think for the Galaxy...

https://github.com/n8fr8/orbot/releases/tag/16.0.6-BETA-2-tor-0.3.5.8

**Comment by n8fr8** [comment]
In summary, for some reason, the Galaxy doesn't unpack the tor binary as other platforms do, so we have to load it from the APK zip file. However, our code for doing that was not unzipping the tor binary file correctly, but it took me a very long time to figure that out.

**Comment by pgerber** [comment]
Update didn't work. Got an "App not installed" but reinstall worked and Tor is now working properly.

@yilmzfurkan, want to test if it now work for you too?

Logs from the attempted update:

```
03-26 14:19:31.428  3444  4469 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/Download/Orbot-16.0.6-BETA-2-tor-0.3.5.8-fullperm-universal-release.apk typ=application/vnd.android.package-archive cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallStart (has extras)} from uid 10128
03-26 14:19:31.432   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-26 14:19:31.442 28958 28958 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@43e6466
03-26 14:19:31.450   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-26 14:19:31.459  4410  4424 W System  : A resource failed to call close. 
03-26 14:19:31.465   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-26 14:19:31.466  3444  4469 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/Download/Orbot-16.0.6-BETA-2-tor-0.3.5.8-fullperm-universal-release.apk typ=application/vnd.android.package-archive flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallStaging (has extras)} from uid 10032
03-26 14:19:31.482   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-26 14:19:31.488 28958 28958 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@9906af9
03-26 14:19:31.516   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-26 14:19:31.560  3444  3494 I LaunchCheckinHandler: Displayed com.google.android.packageinstaller/com.android.packageinstaller.InstallStaging,wp,ca,77
03-26 14:19:31.533   947  1389 I chatty  : uid=1000(system) HwBinder:947_1 identical 1 line
03-26 14:19:31.550   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-26 14:19:31.560  3444  3494 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.InstallStaging: +65ms (total +107ms)
03-26 14:19:31.566   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-26 14:19:31.582  3444  4469 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package4865593731934013668.apk flg=0x2010000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.DeleteStagedFileOnResult (has extras)} from uid 10032
03-26 14:19:31.583   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 7, app_layer_count: 6, gpu_target_index: 6, display type: 0
03-26 14:19:31.600   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 7, app_layer_count: 6, gpu_target_index: 6, display type: 0
03-26 14:19:31.602 28958 28958 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@9b54fb2
03-26 14:19:31.607  3444  4657 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package4865593731934013668.apk flg=0x10000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity (has extras)} from uid 10032
03-26 14:19:31.617   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 7, app_layer_count: 6, gpu_target_index: 6, display type: 0
03-26 14:19:31.633   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 7, app_layer_count: 6, gpu_target_index: 6, display type: 0
03-26 14:19:31.641 28958 28958 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b9d7998
03-26 14:19:31.650   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 7, app_layer_count: 6, gpu_target_index: 6, display type: 0
03-26 14:19:31.683   947  1389 I chatty  : uid=1000(system) HwBinder:947_1 identical 2 lines
03-26 14:19:31.700   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 7, app_layer_count: 6, gpu_target_index: 6, display type: 0
03-26 14:19:31.711  2720  2720 D SurfaceFlinger: duplicate layer name: changing Surface(name=AppWindowToken{52473ef token=Token{3fcc8ce ActivityRecord{c65f9c9 u0 com.google.android.packageinstaller/com.android.packageinstaller.InstallStaging t5271}}})/@0xc00c583 - animation-leash to Surface(name=AppWindowToken{52473ef token=Token{3fcc8ce ActivityRecord{c65f9c9 u0 com.google.android.packageinstaller/com.android.packageinstaller.InstallStaging t5271}}})/@0xc00c583 - animation-leash#1
03-26 14:19:31.717   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
03-26 14:19:31.722  3444  3494 I LaunchCheckinHandler: Displayed com.google.android.packageinstaller/com.android.packageinstaller.DeleteStagedFileOnResult,wp,ca,128
03-26 14:19:31.726  3444  3494 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity: +91ms (total +122ms)
03-26 14:19:31.734   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:31.750   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:31.767   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 8, app_layer_count: 7, gpu_target_index: 7, display type: 0
03-26 14:19:31.918   947  1389 I chatty  : uid=1000(system) HwBinder:947_1 identical 9 lines
03-26 14:19:31.935   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 8, app_layer_count: 7, gpu_target_index: 7, display type: 0
03-26 14:19:31.952   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:31.964 12211 12211 D GeckoNetworkManager: Incoming event stop for state OffWithListeners -> null
03-26 14:19:31.964 12211 12211 W GeckoNetworkManager: Invalid event stop for state OffWithListeners
03-26 14:19:31.964 12211 12229 D GeckoBrowserProvider: Expiring history.
03-26 14:19:31.964 12211 12229 D GeckoBrowserProvider: Expiring highlights blocklist.
03-26 14:19:31.965 12211 12229 D GeckoBrowserProvider: Expiring thumbnails.
03-26 14:19:31.969   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.526  3444  4657 I ActivityManager: START u0 {dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package4865593731934013668.apk flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallInstalling (has extras)} from uid 10032
03-26 14:19:32.517   947  1389 I chatty  : uid=1000(system) HwBinder:947_1 identical 10 lines
03-26 14:19:32.535   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.547 28958 28958 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@ed8ee6a
03-26 14:19:32.552   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.573  3444  3799 I ActivityManager: START u0 {dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package4865593731934013668.apk flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallFailed (has extras)} from uid 10032
03-26 14:19:32.567   947  1389 I chatty  : uid=1000(system) HwBinder:947_1 identical 1 line
03-26 14:19:32.585   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.593 28958 28958 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6c23fe9
03-26 14:19:32.601   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.607 28958 28958 D InstallFailed: Installation status code: 1
03-26 14:19:32.618   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.641  3444  3494 I LaunchCheckinHandler: Displayed com.google.android.packageinstaller/com.android.packageinstaller.InstallFailed,wp,ca,54
03-26 14:19:32.635   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.642  3444  3494 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.InstallFailed: +46ms (total +94ms)
03-26 14:19:32.651 28958 28975 D OpenGLRenderer: endAllActiveAnimators on 0x734a767f00 (RippleDrawable) with handle 0x735eca03e0
03-26 14:19:32.653   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.685   947  1389 I chatty  : uid=1000(system) HwBinder:947_1 identical 2 lines
03-26 14:19:32.768   947  1389 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-26 14:19:32.992  6009  6160 D Tun2Socks: INFO(tun2socks): UDP: from device 1500 bytes
03-26 14:19:32.992  6009  6160 D Tun2Socks: INFO(tun2socks): UDP: from device 1179 bytes
03-26 14:19:33.209  6009  6160 D Tun2Socks: INFO(tun2socks): UDP: from device 40 bytes
```

**Comment by yilmzfurkan** [comment]
@pgerber @n8fr8 It connects to Tor but I see some unexpected behavior it says it has connected but actually I couldn't connect to any websites and my wi-fi gets a exclamation mark. I can guarantee that it has nothing to do with my network I tested this at least 5-6 times. So here is a video about it: control my wi-fi how it will have a exclamation mark after connecting to Tor and I cant enter any website (also check my wi-fi when I disconnect from Tor it will fix itself). Also something little the app was hiding from recents screen in older versions now it doesn't. Here is a video and a huge logcat if its gonna help.

video: https://streamable.com/iesvf

[logcat_03-26-2019_21-39-14.txt](https://github.com/n8fr8/orbot/files/3009767/logcat_03-26-2019_21-39-14.txt)

**Comment by n8fr8** [comment]
Thanks @yilmzfurkan - I found an issue with pdnsd daemon we use for the VPN feature. That is likely the cause of the issue.

As for recent screens, I had turned that off during development. What do you think - do you like that it is hidden?

**Comment by yilmzfurkan** [comment]
@n8fr8 I like it hidden because my obsession. I don't want to see anything in the recent screen and will swipe it away probably doesn't matter but automatically hiding itself would be better in my opinion.

**Comment by bitmold** [comment]
I think a lot of users expect the app to be in the recent screens. My fear is that having it disappear when a new user leaves the app could mystify Tor for them in a way that might dissuade them from using Orbot/Tor.

That said, maybe this can be a preference that the user sets. If so, I'm inclined to say that the preference should default to Orbot being in the recent screens.

**Comment by yilmzfurkan** [comment]
@bitmold your right about new users I agree with you on that. However an option in settings would be great!

**Comment by bitmold** [comment]
I'll work on this today :+)

**Comment by pgerber** [comment]
As far as I can tell, this issue has been resolved. Thanks @n8fr8. Closing.

P.S. If anyone is still interested in changing the behavior in the most recent view, I recommend opening a new issue or better still a pull request.
