### ISSUE TITLE
no intent / fire browser exception and crash 15.1rc1

### ISSUE THREAD

**Issue by c3ph3us** [guardianproject/orbot#23]
when no browser on phone - crash 

01-20 06:36:28.331 10021-10021/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.torproject.android, PID: 10021
                                                   android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://check.torproject.org/... flg=0x30000000 }
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3930)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3890)
                                                       at android.app.Activity.startActivity(Activity.java:4213)
                                                       at android.app.Activity.startActivity(Activity.java:4181)
                                                       at org.torproject.android.OrbotMainActivity.openBrowser(OrbotMainActivity.java:702)
                                                       at org.torproject.android.OrbotMainActivity.doTorCheck(OrbotMainActivity.java:505)
                                                       at org.torproject.android.OrbotMainActivity.access$200(OrbotMainActivity.java:81)
                                                       at org.torproject.android.OrbotMainActivity$3.onClick(OrbotMainActivity.java:255)
                                                       at android.view.View.performClick(View.java:5204)
                                                       at android.view.View$PerformClick.run(View.java:21156)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5470)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by n8fr8** [comment]
You have no browser at all installed? Why not have Orfox or Orweb?

**Comment by c3ph3us** [comment]
@n8fr8 - i disabled default one after installation as i don't use it - i realized that when exception was thrown :) 

btw did u consider to migrate project to Gradle ? it would  be much easier to build Orbot as android studio has support for ndk(as part of it).

**Comment by bitmold** [comment]
This is really old but this can be closed we no longer open that web page in Orbot ever since Orfox integration was removed
