### ISSUE TITLE
exception net.freehaven.tor.control.TorControlConnection.setConf() 15.1rc1

### ISSUE THREAD

**Issue by c3ph3us** [guardianproject/orbot#25]
01-20 07:00:57.578 2985-3862/? E/AndroidRuntime: FATAL EXCEPTION: Thread-254
                                                 Process: org.torproject.android, PID: 2985
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void net.freehaven.tor.control.TorControlConnection.setConf(java.lang.String, java.lang.String)' on a null object reference
                                                     at org.torproject.android.service.TorService.setExitNode(TorService.java:2355)
                                                     at org.torproject.android.service.TorService.access$400(TorService.java:85)
                                                     at org.torproject.android.service.TorService$IncomingIntentRouter.run(TorService.java:344)
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by bitmold** [comment]
There are null checks on the `TorControlConnection` object at this point and this issue is almost half a decade old so I'm closing it :)
