### ISSUE TITLE
DNS not working in VPN mode

### ISSUE THREAD

**Issue by pgerber** [guardianproject/orbot#327]
With the recent update to Orbot 16.2.0 BETA-2 tor-0.4.2.7 VPN is no longer working. Namely, it would appear that DNS resolution no longer works. In addition, there appears to be a crash when the Orbot is started initially. I've reinstalled Orbot a few times and the crash is reproducible, but only on the first start.

Device: Motorola One Vision
OS: Android 10 (stock)

Crash during first launch:

```
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime: FATAL EXCEPTION: main
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime: Process: org.torproject.android, PID: 20017
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service org.torproject.android.service.vpn.TorVpnService: java.lang.ClassNotFoundException: Didn't find class "org.torproject.android.service.vpn.TorVpnService" on path: DexPathList[[zip file "/data/app/org.torproject.android-TnEOX4f6EAGnMoeyBrouFw==/base.apk"],nativeLibraryDirectories=[/data/app/org.torproject.android-TnEOX4f6EAGnMoeyBrouFw==/lib/arm64, /data/app/org.torproject.android-TnEOX4f6EAGnMoeyBrouFw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at android.app.ActivityThread.handleCreateService(ActivityThread.java:4155)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at android.app.ActivityThread.access$1600(ActivityThread.java:232)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:107)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:241)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:7617)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.torproject.android.service.vpn.TorVpnService" on path: DexPathList[[zip file "/data/app/org.torproject.android-TnEOX4f6EAGnMoeyBrouFw==/base.apk"],nativeLibraryDirectories=[/data/app/org.torproject.android-TnEOX4f6EAGnMoeyBrouFw==/lib/arm64, /data/app/org.torproject.android-TnEOX4f6EAGnMoeyBrouFw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  at android.app.ActivityThread.handleCreateService(ActivityThread.java:4150)
05-01 16:00:05.684 10225 20017 20017 E AndroidRuntime:  ... 8 more
```

Permission denied while trying to start pdnsd:

```
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService: java.io.IOException: Cannot run program "/data/data/org.torproject.android/files/pdnsd": error=13, Permission denied
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         at org.torproject.android.service.vpn.OrbotVpnManager.startDNS(OrbotVpnManager.java:428)
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         at org.torproject.android.service.vpn.OrbotVpnManager.access$1300(OrbotVpnManager.java:64)
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         at org.torproject.android.service.vpn.OrbotVpnManager$2.run(OrbotVpnManager.java:352)
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService: Caused by: java.io.IOException: error=13, Permission denied
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         at java.lang.UNIXProcess.forkAndExec(Native Method)
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         at java.lang.ProcessImpl.start(ProcessImpl.java:141)
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
05-01 16:00:16.825 10225 20073 20118 D OrbotVpnService:         ... 3 more
0
```

full log:
[bugreport-kane_reteu-QSAS30.62-24-3-2020-05-01-16-02-04.txt](https://github.com/guardianproject/orbot/files/4564743/bugreport-kane_reteu-QSAS30.62-24-3-2020-05-01-16-02-04.txt)

**Comment by n8fr8** [comment]
Can you do a fresh install? TorVpnService no longer exists (now merged with OrbotService) and pdnsd shouldn't be executing from that location.

Thanks!

**Comment by n8fr8** [comment]
Ah guess you said you did a fresh install. 

Okay, well beta 3 coming soon. We do have reports of VPN working fine on Pixel and Lineage based ROMs.

**Comment by n8fr8** [comment]
Please test: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-3-tor-0.4.2.7
with a fresh install. Thanks!

**Comment by pgerber** [comment]
Thanks, @n8fr8, the new release is looking better. DNS/VPN is working fine now. However, there is still a crash when starting Orbot after the install and when it is started automatically after a reboot. A second or third attempt to open it usually works. As far as I can tell the startup error is still the same as in the BETA-2 release (see also log excerpt above):

```
--------- beginning of crash
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime: FATAL EXCEPTION: main
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime: Process: org.torproject.android, PID: 6049
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service org.torproject.android.service.vpn.TorVpnService: java.lang.ClassNotFoundException: Didn't find class "org.torproject.android.service.vpn.TorVpnService" on path: DexPath
List[[zip file "/data/app/org.torproject.android-jCJQ524lee9_3FZUZwpUcg==/base.apk"],nativeLibraryDirectories=[/data/app/org.torproject.android-jCJQ524lee9_3FZUZwpUcg==/lib/arm64, /data/app/org.torproject.android-jCJQ524lee9_3FZUZwpUcg==/base.apk!/lib/arm64-v8a, /system/lib64, /sys
tem/product/lib64]]
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at android.app.ActivityThread.handleCreateService(ActivityThread.java:4155)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at android.app.ActivityThread.access$1600(ActivityThread.java:232)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:107)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:241)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:7617)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.torproject.android.service.vpn.TorVpnService" on path: DexPathList[[zip file "/data/app/org.torproject.android-jCJQ524lee9_3FZUZwpUcg==/base.apk"],nativeLibrar
yDirectories=[/data/app/org.torproject.android-jCJQ524lee9_3FZUZwpUcg==/lib/arm64, /data/app/org.torproject.android-jCJQ524lee9_3FZUZwpUcg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  at android.app.ActivityThread.handleCreateService(ActivityThread.java:4150)
05-01 20:36:02.272 10228  6049  6049 E AndroidRuntime:  ... 8 more
```

**Comment by pgerber** [comment]
I also wonder if there is something wrong with the versioning. Play wants me update to the older version 16.1.4-RC-1-tor-0.4.2.5-rc.

**Comment by n8fr8** [comment]
ah ha, i think i know what it is. thanks for the clues!

**Comment by goovich** [comment]
> Please test: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-3-tor-0.4.2.7
> with a fresh install. Thanks!

Thank you for this release. Finally orbot seems to be fixed. Can use as proxy or as VPN!

**Comment by n8fr8** [comment]
> I also wonder if there is something wrong with the versioning. Play wants me update to the older version 16.1.4-RC-1-tor-0.4.2.5-rc.

The issue with versioning is that the Google Play build is done as a per-architecture release, separating all the binaries to make the app smaller in distribution. This modifies the version code to prepend a numbering scheme to it, causing the issue you are seeing. 

Once you upgrade through Play this won't happen, but def tricky to mix and match between Play, APK, F-Droid, etc.

**Comment by n8fr8** [comment]
@pgerber new build here with a change that hopefully stops the crash you were seeing:
https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-4-tor-0.4.2.7

Also, try the arm64 build, that may resolve the Play version issue.

**Comment by pgerber** [comment]
I can confirm that the crash is gone in 16.2.0-BETA-4. Thanks @n8fr8.

Also, using the arm64 build indeed fixed the issue with Play.

**Comment by goovich** [comment]
Yeap, orbot starts at first attempt. No crash. Thanks! @n8fr8
