### ISSUE TITLE
Error during installation on android 9  (java.lang.IllegalStateException: Drag shadow dimensions must be positive)

### ISSUE THREAD

**Issue by srodriguez20** [guardianproject/orbot#342]
Trying to install the application on Android 9 devices, the installation fails showing the following error:

java.lang.IllegalStateException: Drag shadow dimensions must be positive
     FATAL EXCEPTION: Thread-2
Process: org.torproject.android, PID: 12878
```
java.lang.IllegalStateException: Drag shadow dimensions must be positive
	at android.view.View.startDragAndDrop(View.java:24023)
	at android.widget.Editor.startDragAndDrop(Editor.java:1165)
	at android.widget.Editor.performLongClick(Editor.java:1191)
	at android.widget.TextView.performLongClick(TextView.java:11346)
	at android.view.View.performLongClick(View.java:6653)
	at android.view.View$CheckForLongPress.run(View.java:25850)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:102)
	at androidx.test.espresso.action.Tap$2.a(Tap.java:7)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

That error was obtained by trying to use the application in Firebase Test lab.

**Comment by bitmold** [comment]
Looking into this now, thanks for reporting this...

https://stackoverflow.com/questions/52073822/illegalstateexception-drag-shadow-dimensions-must-be-positive

**Comment by bitmold** [comment]
Orbot does seem to install fine on Android 9, I think this error exists in the scope of running instrumentation apps on Orbot and pertains to rigging it up with Firebase Test Labs. Notably none of the Orbot application code ever invokes `View.startDragAndDrop`

I wasn't able to reproduce this on Firebase what was the exact test configuration that you used? I did notice that running the default "robo test" on the app passed on API 26 but returned an inconclusive result on "Android 28".
