### ISSUE TITLE
Moat Error Dialog Fragment Can Crash App

### ISSUE THREAD

**Issue by bitmold** [guardianproject/orbot#353]
Orbot can crash if the Moat Error Dialog Fragment is attempted to open after the Activity that fires it off is killed. In an earlier pull request we had discussed wrapping the call to that invoke that dialog in `if (!isFinishing()) { ... } ` but that didn't seem to work. 

```
2020-06-16 12:13:20.005 17976-17976/org.torproject.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.torproject.android, PID: 17976
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
        at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:155)
        at org.torproject.android.ui.onboarding.MoatActivity.displayError(MoatActivity.java:438)
        at org.torproject.android.ui.onboarding.MoatActivity.access$800(MoatActivity.java:60)
        at org.torproject.android.ui.onboarding.MoatActivity$4.onErrorResponse(MoatActivity.java:361)
        at com.android.volley.Request.deliverError(Request.java:617)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6640)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

**Comment by bitmold** [comment]
We no longer use this dialog fragment, closing
