### ISSUE TITLE
Crash when pasting bridges [With logs]

### ISSUE THREAD

**Issue by Thewisem** [guardianproject/orbot#494]
As the title says, paste custom bridges ans it crashes
FATAL EXCEPTION: main
Process: org.torproject.android, PID: 31782
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.Editor$SelectionModifierCursorController.isDragAcceleratorActive()' on a null object reference
	at android.widget.Editor.updateFloatingToolbarVisibility(Editor.java:1554)
	at android.widget.Editor.onTouchEvent(Editor.java:1501)
	at android.widget.TextView.onTouchEvent(TextView.java:10105)
	at android.view.View.dispatchTouchEvent(View.java:10920)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:696)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:623)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1914)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3247)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:585)
	at android.view.View.dispatchPointerEvent(View.java:11149)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5222)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5071)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4575)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4628)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4594)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4731)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4602)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4788)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4575)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4628)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4594)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4602)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4575)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7205)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7137)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7098)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7316)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7279)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:634)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by bitmold** [comment]
We have an entirely new UI where you can paste bridges without it crashing, so closing this very old issue.
