### ISSUE TITLE
library "libtun2socks.so" not found

### ISSUE THREAD

**Issue by hardikhari96** [guardianproject/orbot#541]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.torproject.android, PID: 26936
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libtun2socks.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.torproject.android.service.vpn.Tun2Socks.<clinit>(Tun2Socks.java:53)
        at org.torproject.android.service.vpn.Tun2Socks.init(Tun2Socks.java:57)
        at org.torproject.android.service.vpn.OrbotVpnManager.<init>(OrbotVpnManager.java:85)
        at org.torproject.android.service.OrbotService.onCreate(OrbotService.java:484)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4511)
        at android.app.ActivityThread.access$100(ActivityThread.java:306)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2176)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8276)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
I/Process: Sending signal. PID: 26936 SIG: 9

_Originally posted by @hardikhari96 in https://github.com/guardianproject/orbot/issues/20#issuecomment-968086206_

**Comment by bitmold** [comment]
It seems like you didn't follow the instructions in the BUILD.md file: https://github.com/guardianproject/orbot/blob/master/BUILD.md

If this issue persists after you've done all of the Android NDK steps let's talk more...
