### ISSUE TITLE
Starting/Stopping Orbot Rapidly will Cause Service Connection to Leak

### ISSUE THREAD

**Issue by bitmold** [guardianproject/orbot#553]
```
  android.app.ServiceConnectionLeaked: Service org.torproject.android.service.OrbotService has leaked ServiceConnection org.torproject.android.service.OrbotService$1@376a954 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1841)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1699)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1685)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1817)
        at android.app.ContextImpl.bindService(ContextImpl.java:1757)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:762)
        at org.torproject.android.service.OrbotService.startTorService(OrbotService.java:855)
        at org.torproject.android.service.OrbotService.startTor(OrbotService.java:703)
        at org.torproject.android.service.OrbotService.-$$Nest$mstartTor(Unknown Source:0)
        at org.torproject.android.service.OrbotService$IncomingIntentRouter.run(OrbotService.java:1428)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```
After this exception the next time you try to start tor the app will crash ...

**Comment by bitmold** [comment]
This has been fixed for a while now
