### ISSUE TITLE
Apps VPN mode crash

### ISSUE THREAD

**Issue by Sk8nn3r** [guardianproject/orbot#69]
Hi,

I've been trying to build orbot using the guide from BUILD file.
I've successfully managed to build it but each time I 
- Turn on Apps VPN Mode
- Choose all apps
- Go back
- Give it permissions

the app crashes and keeps doing so until all data is cleared
From the log I've found out that libtun2socks.so is missing.
Would you mind helping me solve this?
Cheers

> 04-27 16:21:01.336 27458-27458/org.torproject.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: org.torproject.android, PID: 27458
                                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.torproject.android-1/base.apk", zip file "/data/app/org.torproject.android-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.torproject.android-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.torproject.android-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libtun2socks.so"
                                                                            at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                                            at java.lang.System.loadLibrary(System.java:1562)
                                                                            at org.torproject.android.service.vpn.Tun2Socks.<clinit>(Tun2Socks.java:35)
                                                                            at org.torproject.android.service.vpn.Tun2Socks.init(Tun2Socks.java:0)
                                                                            at org.torproject.android.service.vpn.OrbotVpnManager.<init>(OrbotVpnManager.java:96)
                                                                            at org.torproject.android.service.vpn.TorVpnService.onCreate(TorVpnService.java:29)
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3192)
                                                                            at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by n8fr8** [comment]
Are you running the "ndk-build" command to generate the: libtun2socks.so

That might not be in the build info... I will check.

**Comment by Sk8nn3r** [comment]
I've ran ndk-build in orbotservice/src/main
I can tell I'm not doing something right since my final debug apk filesize is 8,2Mb which is not even close to your releases

**Comment by Sk8nn3r** [comment]
Tried to add libtun2socks.so to /data/app/org.torproject.android-1/lib/arm64 ,  still having the same error.

Here's the build process (Ubuntu 16.04 64bit)

- Cloned the repo
- Exported NDK and SDK home
- Inited all submodules
- Changed orbotservice/src/main/jni/Application.mk toolchain version to 4.9
- ndk-build in orbotservice/src/main
- Changed external/Makefile toolchain to 4.9 and commented line 66 since my NDK doesn't have setup.mk file
- make -C external from orbot folder
- verified tor and polipo binaries
- assembled the debug with gradle / android-studio

I've tried it on Nexus 6P (angler) with a pure AOSP build and with google's factory image. Both result in same error

**Comment by bitmold** [comment]
I think this can be closed because it's for a version of Orbot third party dependencies that were used 3+ years ago and aren't today anymore. Based off of their last comment here, perhaps @Sk8nn3r didn't run the series of `mv` commands mentioned in the BUILD file? 

Closing this now, @Sk8nn3r if you are trying to build Orbot today and are running into the same/new problems please feel free to open a new issue here
