### ISSUE TITLE
Orbot 17: startup on boot crash

### ISSUE THREAD

**Issue by syphyr** [guardianproject/orbot#812]
When "Start Orbot on Boot" is enabled on 17.0.0-ALPHA-4-tor.0.4.7.10, a fatal exception occurs when Orbot attempts to automatically start  on boot.  Manually starting Orbot after the system boots works fine.

```
02-13 09:31:31.175  1422  1422 E AndroidRuntime: FATAL EXCEPTION: main
02-13 09:31:31.175  1422  1422 E AndroidRuntime: Process: org.torproject.android, PID: 1422
02-13 09:31:31.175  1422  1422 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.torproject.android.OrbotApp: java.lang.IllegalStateException: WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5451)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: Caused by: java.lang.IllegalStateException: WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at androidx.work.WorkManager.getInstance(WorkManager.java:165)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at org.torproject.android.service.util.Prefs.initWeeklyWorker(Prefs.java:64)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at org.torproject.android.OrbotApp.onCreate(OrbotApp.java:29)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
02-13 09:31:31.175  1422  1422 E AndroidRuntime: 	... 8 more
```

**Comment by syphyr** [comment]
When looking at the official doc for WorkManager here: https://developer.android.com/guide/background/persistent/configuration/custom-configuration#custom-config

This seems to be the problem:

```
Note: If you call the deprecated no-parameter WorkManager.getInstance() method before WorkManager has been initialized, the method throws an exception. You should always use the WorkManager.getInstance(Context) method, even if you're not customizing WorkManager.
```

**Comment by syphyr** [comment]
I am trying to add `WorkManager.initialize(Context, new Configuration.Builder().build());` before `WorkManager.getInstance()` but I cant figure out how to get the right `Context`

https://github.com/guardianproject/orbot/blob/83f245c77b417066bc7ca40f910bed29bce5851e/orbotservice/src/main/java/org/torproject/android/service/util/Prefs.java#L64

**Comment by syphyr** [comment]
@n8fr8 this crash on startup started to occur with 1fcceebf9728ef33a945afc43b1b8b44b7ab41c7.  Do you have any suggestions on how to initialize the correct "Context" with WorkManager?  I am having some problems trying to figure out the correct way of initializing WorkManager before calling it.

**Comment by xyz-nobody** [comment]
Same with version 17.0.0 BETA 5, Orbot does not start by default at boot

**Comment by n8fr8** [comment]
I've made the fix last week, but haven't put a release out.

**Comment by xyz-nobody** [comment]
In any case thank you for this great work.
Orbot is really great.

Do you know when you will push a next beta or rc?

**Comment by syphyr** [comment]
> I've made the fix last week, but haven't put a release out.

I can confirm that 3dd0fdb72a16b15eecdc6d6888e749355813b0c7 fixes the startup crash.  Thank you!

**Comment by syphyr** [comment]
Fixed
